In [1]:
import pandas as pd

df= pd.read_csv('fmodbid_to_PDB-ID.csv')
df.head()

  fmodbid PDB-ID
0   X17ZX   1BL6
1   XV51P   1BL7
2   XYZ2P   1BMK
3   P5JZX   1KV1
4   P4JNP   1KV2

In [2]:
df_fmo = pd.read_csv('ifie_data\\P2LRP.csv')
df_fmo.head()

,Unnamed: 0,frag_NumFragment number.,ChainChain species.,Res #Residue number.,"RES3-letter code of amino acid residue, ligand and solvent molecule.",FCHARGEFormal charge [e].,q_MullikenFragment charge evaluated by Mulliken charge [e].,q_NPAFragment charge evaluated by natural population analysis(NPA) charge [e].,DISTDistance from Ligand [Å].,TotalIFIE at MP2 level [kcal/mol].,ESElectro static interaction energy by PIEDA [kcal/mol].,EXExchange-repulsion energy by PIEDA [kcal/mol].,CT+mixCharge transfer and mixing terms energy by PIEDA [kcal/mol].,DI(MP2)Dispersion energy by PIEDA [kcal/mol].,q(I=>J)Charge transfer value from I to J fragmens [e].
0,0,1,A,6,PRO,1,0.850,0.901,15.266,-0.129,-0.129,0.0,0.0,0.0,0.0
1,1,2,A,7,THR,0,0.080,0.060,18.350,0.026,0.026,0.0,0.0,0.0,0.0
2,2,3,A,8,PHE,0,0.018,0.013,13.068,-0.035,-0.035,0.0,0.0,0.0,0.0
3,3,4,A,9,TYR,0,-0.036,-0.030,14.312,0.011,0.011,0.0,0.0,0.0,0.0
4,4,5,A,10,ARG,1,0.948,0.972,16.001,-0.611,-0.611,0.0,0.0,0.0,0.0

In [3]:
df_kinase = pd.read_csv('Kinase_p38.csv')
df_kinase.head()

,Index,PROTEIN_ACCESSION,Structure,CMPD_CHEMBLID,MOL_PREF_NAME,CANONICAL_SMILES,PDB_ID,Molecular_Weight,Distribution,NAssay,Mean(IC50),StdDev(IC50),Median(IC50),Mean(pIC50),StdDev(pIC50),Median(pIC50)
0,1,Q16539,NaN,CHEMBL96741,-,Fc1ccc(cc1)c2ncn(CC3CC3)c2c4ccncc4,1BL6,293.33814,NaN,2,160.000000,0.000000,160.0,6.795880,0.000000,6.795880
1,1,Q16539,NaN,CHEMBL274064,SB-220025,Nc1nccc(n1)c2c(ncn2C3CCNCC3)c4ccc(F)cc4,1BL7,338.38206,NaN,4,19.500000,0.500000,19.5,7.710108,0.011138,7.710108
2,1,Q16539,NaN,CHEMBL590753,-,Nc1nccc(n1)c2c(ncn2CC3CC3)c4ccc(F)cc4,1BMK,309.34084,NaN,1,25.000000,0.000000,25.0,7.602060,0.000000,7.602060
3,1,Q16539,NaN,CHEMBL87277,-,Cn1nc(cc1NC(=O)Nc2ccc(Cl)cc2)C(C)(C)C,"1KV1, 3O8P, 3O8T, 3O8U, 3OBJ, 3OC1",306.79055,NaN,2,18900.000000,2100.000000,18900.0,4.726236,0.048455,4.726236
4,1,Q16539,NaN,CHEMBL103667,DORAMAPIMOD,Cc1ccc(cc1)n2nc(cc2NC(=O)Nc3ccc(OCCN4CCOCC4)c5...,1KV2,527.65717,NaN,13,89.854615,117.536082,44.0,7.421859,0.589448,7.356547

In [4]:
df_kinase['PDB_ID']

0                                   1BL6
1                                   1BL7
2                                   1BMK
3     1KV1, 3O8P, 3O8T, 3O8U, 3OBJ, 3OC1
4                                   1KV2
                     ...
80                                  4AA5
81                                  4AAC
82                                  4KIN
83                                  4KIP
84                                  4KIQ
Name: PDB_ID, Length: 85, dtype: object

In [5]:
df_merge = pd.merge(df, df_kinase, left_on='PDB-ID', right_on='PDB_ID')
df_merge.head()

,fmodbid,PDB-ID,Index,PROTEIN_ACCESSION,Structure,CMPD_CHEMBLID,MOL_PREF_NAME,CANONICAL_SMILES,PDB_ID,Molecular_Weight,Distribution,NAssay,Mean(IC50),StdDev(IC50),Median(IC50),Mean(pIC50),StdDev(pIC50),Median(pIC50)
0,X17ZX,1BL6,1,Q16539,NaN,CHEMBL96741,-,Fc1ccc(cc1)c2ncn(CC3CC3)c2c4ccncc4,1BL6,293.33814,NaN,2,160.000000,0.000000,160.0,6.795880,0.000000,6.795880
1,P55ZP,1BL6,1,Q16539,NaN,CHEMBL96741,-,Fc1ccc(cc1)c2ncn(CC3CC3)c2c4ccncc4,1BL6,293.33814,NaN,2,160.000000,0.000000,160.0,6.795880,0.000000,6.795880
2,XV51P,1BL7,1,Q16539,NaN,CHEMBL274064,SB-220025,Nc1nccc(n1)c2c(ncn2C3CCNCC3)c4ccc(F)cc4,1BL7,338.38206,NaN,4,19.500000,0.500000,19.5,7.710108,0.011138,7.710108
3,XYZ2P,1BMK,1,Q16539,NaN,CHEMBL590753,-,Nc1nccc(n1)c2c(ncn2CC3CC3)c4ccc(F)cc4,1BMK,309.34084,NaN,1,25.000000,0.000000,25.0,7.602060,0.000000,7.602060
4,P4JNP,1KV2,1,Q16539,NaN,CHEMBL103667,DORAMAPIMOD,Cc1ccc(cc1)n2nc(cc2NC(=O)Nc3ccc(OCCN4CCOCC4)c5...,1KV2,527.65717,NaN,13,89.854615,117.536082,44.0,7.421859,0.589448,7.356547

In [12]:
df_merge[['fmodbid', 'PDB_ID', 'CANONICAL_SMILES', 'Median(IC50)']].to_pickle('fmodbid_simles.pkl')

In [13]:
df = pd.read_pickle('fmodbid_simles.pkl')
df.head()

,fmodbid,PDB_ID,CANONICAL_SMILES,Median(IC50)
0,X17ZX,1BL6,Fc1ccc(cc1)c2ncn(CC3CC3)c2c4ccncc4,160.0
1,P55ZP,1BL6,Fc1ccc(cc1)c2ncn(CC3CC3)c2c4ccncc4,160.0
2,XV51P,1BL7,Nc1nccc(n1)c2c(ncn2C3CCNCC3)c4ccc(F)cc4,19.5
3,XYZ2P,1BMK,Nc1nccc(n1)c2c(ncn2CC3CC3)c4ccc(F)cc4,25.0
4,P4JNP,1KV2,Cc1ccc(cc1)n2nc(cc2NC(=O)Nc3ccc(OCCN4CCOCC4)c5...,44.0

In [8]:
df['fmodbid']=="X17ZX"

0      True
1     False
2     False
3     False
4     False
      ...
81    False
82    False
83    False
84    False
85    False
Name: fmodbid, Length: 86, dtype: bool

In [9]:
df[df['fmodbid']=="X17ZX"]["CANONICAL_SMILES"]

0    Fc1ccc(cc1)c2ncn(CC3CC3)c2c4ccncc4
Name: CANONICAL_SMILES, dtype: object

In [10]:
df[df['fmodbid']=="X17ZX"]["CANONICAL_SMILES"][0]

'Fc1ccc(cc1)c2ncn(CC3CC3)c2c4ccncc4'

In [11]:
df_kinase.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85 entries, 0 to 84
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Index              85 non-null     int64
 1   PROTEIN_ACCESSION  85 non-null     object
 2   Structure          0 non-null      float64
 3   CMPD_CHEMBLID      85 non-null     object
 4   MOL_PREF_NAME      85 non-null     object
 5   CANONICAL_SMILES   85 non-null     object
 6   PDB_ID             85 non-null     object
 7   Molecular_Weight   85 non-null     float64
 8   Distribution       0 non-null      float64
 9   NAssay             85 non-null     int64
 10  Mean(IC50)         85 non-null     float64
 11  StdDev(IC50)       85 non-null     float64
 12  Median(IC50)       85 non-null     float64
 13  Mean(pIC50)        85 non-null     float64
 14  StdDev(pIC50)      85 non-null     float64
 15  Median(pIC50)      85 non-null     float64
dtypes: float64(9), int64(2), object(5)
memory usage: 10.8+ KB